# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'base.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 795)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 700))
        MainWindow.setStyleSheet("QPushButton {\n"
"font-size: 17px;\n"
"}"
"QListView {"
    "show-decoration-selected: 1;"
"}\n"
"QListView::item:alternate {"
    "background: #EEEEEE;"
"}\n"
"QListView::item:selected:!active {"
    "background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ABAFE5, stop: 1 #8588B2);"
"}\n"

"QListView::item:selected:active {"
    "background: #AA14F0;\n"
    "border: 0px solid red;"
"}\n"

"QListView::item:hover {"
    "background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(5, 13, 25), stop:1 #AA14F0);"
"}"
)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.content = QtWidgets.QFrame(self.centralwidget)
        self.content.setStyleSheet("")
        self.content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content.setObjectName("content")
        self.frame_pages = QtWidgets.QFrame(self.content)
        self.frame_pages.setGeometry(QtCore.QRect(0, 0, 1000, 721))
        self.frame_pages.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(5, 13, 25), stop:1 #F8485E);")
        self.frame_pages.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_pages.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pages.setObjectName("frame_pages")
        self.dropdown_menu = QtWidgets.QListView(self.frame_pages)
        self.dropdown_menu.setGeometry(QtCore.QRect(80, 140, 241, 501))
        self.dropdown_menu.setMinimumSize(QtCore.QSize(100, 0))
        self.dropdown_menu.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.dropdown_menu.setSpacing(2)
        self.dropdown_menu.setObjectName("dropdown_menu")
        self.dropdown_menu_2 = QtWidgets.QListView(self.frame_pages)
        self.dropdown_menu_2.setGeometry(QtCore.QRect(400, 140, 521, 501))
        self.dropdown_menu_2.setMinimumSize(QtCore.QSize(100, 0))
        self.dropdown_menu_2.setStyleSheet("")
        self.dropdown_menu_2.setObjectName("dropdown_menu_2")
        self.top_bar = QtWidgets.QFrame(self.frame_pages)
        self.top_bar.setGeometry(QtCore.QRect(0, 0, 1000, 71))
        self.top_bar.setMinimumSize(QtCore.QSize(0, 50))
        self.top_bar.setMaximumSize(QtCore.QSize(16777215, 100))
        self.top_bar.setStyleSheet("background-color: rgb(5, 13, 25);")
        self.top_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.top_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_bar.setObjectName("top_bar")
        self.frame = QtWidgets.QFrame(self.top_bar)
        self.frame.setGeometry(QtCore.QRect(200, 0, 791, 70))
        self.frame.setStyleSheet("QPushButton {\n"
"border: 1px solid gray;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_2 = QtWidgets.QPushButton(self.frame)
        self.button_2.setMinimumSize(QtCore.QSize(0, 50))
        self.button_2.setStyleSheet("QPushButton {\n"
"color: white;\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:1, stop:0 rgb(5, 13, 25), stop:1 #F8485E);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(5, 13, 25), stop:1 #AA14F0);;\n"
"}")
        self.button_2.setObjectName("button_2")
        self.horizontalLayout.addWidget(self.button_2)
        self.button_5 = QtWidgets.QPushButton(self.frame)
        self.button_5.setMinimumSize(QtCore.QSize(0, 50))
        self.button_5.setStyleSheet("QPushButton {\n"
"color: white;\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:1, stop:0 rgb(5, 13, 25), stop:1 #F8485E);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(5, 13, 25), stop:1 #AA14F0);;\n"
"}")
        self.button_5.setObjectName("button_5")
        self.horizontalLayout.addWidget(self.button_5)
        self.button_1 = QtWidgets.QPushButton(self.frame)
        self.button_1.setMinimumSize(QtCore.QSize(0, 50))
        self.button_1.setStyleSheet("QPushButton {\n"
"color: white;\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:1, stop:0 rgb(5, 13, 25), stop:1 #F8485E);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(5, 13, 25), stop:1 #AA14F0);;\n"
"}")
        self.button_1.setObjectName("button_1")
        self.horizontalLayout.addWidget(self.button_1)
        self.button_4 = QtWidgets.QPushButton(self.frame)
        self.button_4.setMinimumSize(QtCore.QSize(0, 50))
        self.button_4.setStyleSheet("QPushButton {\n"
"color: white;\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:1, stop:0 rgb(5, 13, 25), stop:1 #F8485E);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(5, 13, 25), stop:1 #AA14F0);;\n"
"}")
        self.button_4.setObjectName("button_4")
        self.horizontalLayout.addWidget(self.button_4)
        self.button_3 = QtWidgets.QPushButton(self.frame)
        self.button_3.setMinimumSize(QtCore.QSize(0, 50))
        self.button_3.setStyleSheet("QPushButton {\n"
"color: white;\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:1, stop:0 rgb(5, 13, 25), stop:1 #F8485E);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(5, 13, 25), stop:1 #AA14F0);;\n"
"}")
        self.button_3.setObjectName("button_3")
        self.horizontalLayout.addWidget(self.button_3)
        self.label_2 = QtWidgets.QLabel(self.top_bar)
        self.label_2.setGeometry(QtCore.QRect(30, 20, 171, 31))
        self.label_2.setStyleSheet("color: white;\n"
"font-size: 25px;\n"
"font-weight: bold;")
        self.label_2.setObjectName("label_2")
        self.dropdown_box = QtWidgets.QFrame(self.frame_pages)
        self.dropdown_box.setGeometry(QtCore.QRect(200, 70, 161, 0))
        self.dropdown_box.setMinimumSize(QtCore.QSize(0, 0))
        self.dropdown_box.setMaximumSize(QtCore.QSize(16777215, 0))
        self.dropdown_box.setStyleSheet("QPushButton {\n"
"color: white;\n"
"background-color: rgb(5, 13, 25); \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(5, 13, 25), stop:1 #AA14F0);;\n"
"}")
        self.dropdown_box.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dropdown_box.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dropdown_box.setObjectName("dropdown_box")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.dropdown_box)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.button_8 = QtWidgets.QPushButton(self.dropdown_box)
        self.button_8.setMinimumSize(QtCore.QSize(0, 40))
        self.button_8.setObjectName("button_8")
        self.verticalLayout_2.addWidget(self.button_8)
        self.button_6 = QtWidgets.QPushButton(self.dropdown_box)
        self.button_6.setMinimumSize(QtCore.QSize(0, 40))
        self.button_6.setObjectName("button_6")
        self.verticalLayout_2.addWidget(self.button_6)
        self.button_7 = QtWidgets.QPushButton(self.dropdown_box)
        self.button_7.setMinimumSize(QtCore.QSize(0, 40))
        self.button_7.setObjectName("button_7")
        self.verticalLayout_2.addWidget(self.button_7)
        self.frame_2 = QtWidgets.QFrame(self.content)
        self.frame_2.setGeometry(QtCore.QRect(0, 720, 1001, 71))
        self.frame_2.setStyleSheet("background-color: rgb(5, 13, 25);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(320, 20, 311, 31))
        self.label_3.setStyleSheet("font-size: 15px;\n"
"font-weight: bold;\n"
"color:white;")
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.content)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ECU ProTech 2021"))
        self.button_2.setText(_translate("MainWindow", "Immobilizer"))
        self.button_5.setText(_translate("MainWindow", "Airbag"))
        self.button_1.setText(_translate("MainWindow", "ECU Repair|Pinout"))
        self.button_4.setText(_translate("MainWindow", "DB Repair|Reset"))
        self.button_3.setText(_translate("MainWindow", "Electronics"))
        self.label_2.setText(_translate("MainWindow", "ECU ProTech"))
        self.button_8.setText(_translate("MainWindow", "PROG|DECODE"))
        self.button_6.setText(_translate("MainWindow", "Pinout|Wiring"))
        self.button_7.setText(_translate("MainWindow", "EEPROM Location"))
        self.label_3.setText(_translate("MainWindow", "Copyrights Reserved by ECUProTechTeam"))
