build:
	pyinstaller "Cartronic Prog.spec"

build-decomp:
	pyinstaller "Catronic Decompiler V1.0.spec"

install:
	pip install -r requirements.txt

decomp:
	python ./utility_scripts/decomp.py

run-decomp:
	./"Catronic Decompiler.exe"

run:
	python main.py

launch: install, run 

install-build: install, build-decomp, run-decomp, build, launch