# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/valid.ui'
#
# Created by: PySide6 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtWidgets


class PromptWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(438, 262)
        self.ValidationWindow = QtWidgets.QWidget(MainWindow)
        self.ValidationWindow.setObjectName("ValidationWindow")
        self.close_button = QtWidgets.QPushButton(self.ValidationWindow)
        self.close_button.setGeometry(QtCore.QRect(290, 200, 111, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.close_button.sizePolicy().hasHeightForWidth())
        self.close_button.setSizePolicy(sizePolicy)
        self.close_button.setObjectName("close_button")
        self.header_text = QtWidgets.QLabel(self.ValidationWindow)
        self.header_text.setGeometry(QtCore.QRect(30, 40, 401, 141))
        self.header_text.setStyleSheet("font-weight: bold;\n"
"font-size: 20px;\n"
"")
        self.header_text.setWordWrap(True)
        self.header_text.setObjectName("header_text")
        MainWindow.setCentralWidget(self.ValidationWindow)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.close_button.setText(_translate("MainWindow", "Exit"))
        self.header_text.setText(_translate("MainWindow", "Sorry, Software License Is Either Invalid Or You are not a Licensed User. Contact The Software Owner for a License"))
