# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'valid.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class PromptWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(524, 372)
        self.ValidationWindow = QtWidgets.QWidget(MainWindow)
        self.ValidationWindow.setObjectName("ValidationWindow")
        self.license_box = QtWidgets.QLineEdit(self.ValidationWindow)
        self.license_box.setGeometry(QtCore.QRect(40, 230, 441, 41))
        self.license_box.setObjectName("license_box")
        self.id_label = QtWidgets.QLabel(self.ValidationWindow)
        self.id_label.setGeometry(QtCore.QRect(40, 100, 161, 16))
        self.id_label.setObjectName("id_label")
        self.key_label = QtWidgets.QLabel(self.ValidationWindow)
        self.key_label.setGeometry(QtCore.QRect(40, 200, 441, 16))
        self.key_label.setObjectName("key_label")
        self.confirm = QtWidgets.QPushButton(self.ValidationWindow)
        self.confirm.setGeometry(QtCore.QRect(370, 310, 111, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.confirm.sizePolicy().hasHeightForWidth())
        self.confirm.setSizePolicy(sizePolicy)
        self.confirm.setObjectName("confirm")
        self.hardware_id_label = QtWidgets.QLabel(self.ValidationWindow)
        self.hardware_id_label.setGeometry(QtCore.QRect(40, 130, 441, 41))
        self.hardware_id_label.setAutoFillBackground(False)
        self.hardware_id_label.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid black;\n"
"")
        self.hardware_id_label.setText("")
        self.hardware_id_label.setObjectName("hardware_id_label")
        self.header_text = QtWidgets.QLabel(self.ValidationWindow)
        self.header_text.setGeometry(QtCore.QRect(110, 30, 321, 51))
        self.header_text.setStyleSheet("font-weight: bold;\n"
"font-size: 20px;\n"
"")
        self.header_text.setObjectName("header_text")
        MainWindow.setCentralWidget(self.ValidationWindow)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ECU PROTECH LICENSE"))
        self.id_label.setText(_translate("MainWindow", "HARDWARE ID"))
        self.key_label.setText(_translate("MainWindow", "ENTER LICENSE KEY (aaaaa-bbbbb-ccccc-ddddd-eeeee)"))
        self.confirm.setText(_translate("MainWindow", "CONFIRM"))
        self.header_text.setText(_translate("MainWindow", "ECU ProTech License 2022"))
